permalink: /:title/
base: https://www.sylvaindurand.org

future: true

kramdown:
  input: GFM

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
